language: python
install:
    - pip install pytest-cov
    - pip install coveralls
python:
    - "3.3"
    - "2.6"
script:
    - py.test --cov-config .coveragerc --cov=. tests/
after_success:
    coveralls